### ISSUE TITLE
Quick code review

### ISSUE THREAD

**Issue by mathieudutour** [KevinGutowski/ToggleGreyscale#1]
Just some things I noticed while looking the code, feel free to ignore

---

You can replace https://github.com/KevinGutowski/ToggleGreyscale/blob/master/src/my-command.js#L1-L10 by
```js
import sketch, {
  UI,
  ShapePath,
  Rectangle,
  Style
} from 'sketch'
// documentation: https://developer.sketchapp.com/reference/api/

export default function() {
```
which avoid duplicating the names (eg. `ShapePath` now appears only once)

---

I would rewrite https://github.com/KevinGutowski/ToggleGreyscale/blob/master/src/my-command.js#L28-L32 as
```js
const artboard = getParentArtboard(correctSelection)
const isRemoving = artboard.layers.find(layer => layer.name == "Greyscale Layer")

...
function getParentArtboard(maybeArtboard) {
  if (maybeArtboard.type == 'Artboard') {
    return maybeArtboard
  }
  return maybeArtboard.getParentArtboard()
}
```

and you can reuse `getParentArtboard` below.

---

You don't need to hoist the variable in your loop. We used to do that when using `var` because they were implicitly hoisted, but `let` isn't. So remove `let frame` and do `let frame = ...` directly.

**Comment by KevinGutowski** [comment]
Heya thanks for leaving some feedback! Always looking for ways I can improve so I really appreciate it :D (sorry for being so slow, I’ve always struggled with Github notifications). 

> You can replace https://github.com/KevinGutowski/ToggleGreyscale/blob/master/src/my-command.js#L1-L10 by
> 
> import sketch, {
>   UI,
>   ShapePath,
>   Rectangle,
>   Style
> } from 'sketch'
> // documentation: https://developer.sketchapp.com/reference/api/
> 
> export default function() {
> which avoid duplicating the names (eg. ShapePath now appears only once)

Not sure I entirely follow. By extracting out classes this way what is gained? Something about ShapePath only appearing once?

-----

> I would rewrite https://github.com/KevinGutowski/ToggleGreyscale/blob/master/src/my-command.js#L28-L32 as
> 
> const artboard = getParentArtboard(correctSelection)
> const isRemoving = artboard.layers.find(layer => layer.name == "Greyscale Layer")
> 
> ...
> function getParentArtboard(maybeArtboard) {
>   if (maybeArtboard.type == 'Artboard') {
>     return maybeArtboard
>   }
>   return maybeArtboard.getParentArtboard()
> }
> and you can reuse getParentArtboard below.

Ahh makes sense. I like the reusability there.

---

> You don't need to hoist the variable in your loop. We used to do that when using var because they were implicitly hoisted, but let isn't. So remove let frame and do let frame = ... directly.

Not entirely sure what you mean there. Are you saying to go from this:

```
for (let i = 0; i < selection.length; i++) {
        let parentArtboard
        let frame
        let layer = selection[i]

        if (layer.type == 'Artboard') {
            ...
        }

        let greyscaleLayer = parentArtboard.layers.find(layer => layer.name == "Greyscale Layer")

        if (isRemoving) {
            ...
        }

        frame = new Rectangle(0, 0, parentArtboard.frame.width, parentArtboard.frame.height)

        if (!greyscaleLayer) {
            ...
        }
    }
```

to this?

```
for (let i = 0; i < selection.length; i++) {
    let parentArtboard
    let frame = new Rectangle(0, 0, parentArtboard.frame.width, parentArtboard.frame.height)
    let layer = selection[i]

    if (layer.type == 'Artboard') {
        ...
    }

    let greyscaleLayer = parentArtboard.layers.find(layer => layer.name == "Greyscale Layer")

    if (isRemoving) {
        ...
    }

    

    if (!greyscaleLayer) {
        ...
    }
}
```

**Comment by mathieudutour** [comment]
> Something about ShapePath only appearing once?

Yes, avoids repeating variables names and imports (you have both `import 'sketch'` and `require('sketch')`

> Are you saying to go from this to this

No, instead of having
```js
for {
  let frame
  ...
  frame = ...
  ...
}
```
You can have
```js
for {
  ...
  const frame = ...
  ...
}
```
The reason why you often see
```js
function () {
  var a
  var b
  ...
  a = ...
  ...
}
```
is because variable declarations with `var` are hoisted, which means that the `var a` is always at the top of the scope (so the beginning of the function here), regardless of where you actually write it.
Example:
```js
function () {
  console.log(a)
  var a = 3
}
```
is actually
```js
function () {
  var a
  console.log(a)
  a = 3
}
```
so it would log `undefined` instead of an error.

This is **not** true for variable declarations using `let` and `const`.
```js
function () {
  console.log(a)
  let a = 3
}
```
would throw an error because `a` isn't defined.

So code like what you have is kind of an old school style that was useful to make the hoisting explicit, but is now unnecessary.

Does that make sense? I know it's a bit confusing 😄

**Comment by KevinGutowski** [comment]
Thanks for the explanation! I think I get it all now. Much simpler logic for figuring out when to remove a the greyscale layer or not. 👍
